### ISSUE TITLE
Month and day shoudl be padded

### ISSUE THREAD

**Issue by devau-remi** [BoboTiG/python-wks-com#2]
Hello!
Month and day should be padded.
The way it's done now, date, eg. for QLD/daily-load, is 2024917, resulting in a NAK answer from the inverter.

https://github.com/BoboTiG/python-wks-com/blob/589d284073d05e235117e95de7967c557d0875fe/src/wks_com/helpers.py#L80

I fixed temporarily with 
`return f"{command}{now.strftime('%Y%m%d')}"`

Anyway, thanks for your great work!!

**Comment by BoboTiG** [comment]
Arf, of course you suggestion is way better 👍 

Would you mind opening a PR? Else I'll be able to change it in a couple of hours.

**Comment by devau-remi** [comment]
It's done.
Thank you!

**Comment by BoboTiG** [comment]
https://github.com/BoboTiG/python-wks-com/releases/tag/v1.0.1, and I updated the documentation to point to the latest release for installation: https://github.com/BoboTiG/python-wks-com/tree/main?tab=readme-ov-file#installation
